const express = require('express');
const { Pool } = require('pg');
const path = require('path');

const app = express();
app.use(express.json());
app.use(express.static(__dirname));

const pool = new Pool({
  connectionString: 'postgresql://hft:kks9XdoLAu1epiWQqeddmMgV9wxg60qK@dpg-d75bt2chg0os73b8vj40-a.oregon-postgres.render.com/hft_soxh',
  ssl: { rejectUnauthorized: false }
});

// Init DB
async function initDB() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS problems (
      id SERIAL PRIMARY KEY,
      type VARCHAR(10) NOT NULL DEFAULT 'CF',
      number VARCHAR(30),
      name VARCHAR(300) NOT NULL,
      contest VARCHAR(300),
      rating VARCHAR(20),
      topic VARCHAR(200),
      hft_relevance VARCHAR(300),
      category VARCHAR(100),
      phase VARCHAR(50),
      solved BOOLEAN DEFAULT FALSE,
      important BOOLEAN DEFAULT FALSE,
      note TEXT DEFAULT '',
      created_at TIMESTAMP DEFAULT NOW(),
      updated_at TIMESTAMP DEFAULT NOW()
    );
  `);
  console.log('DB ready');
}

// Seed problems if table is empty
async function seedProblems() {
  const { rows } = await pool.query('SELECT COUNT(*) FROM problems');
  if (parseInt(rows[0].count) > 0) return;
  console.log('Seeding problems...');

  const lcProblems = [
    // Category 1: DP (25)
    ['LC','10','Regular Expression Matching','','Hard','DP on strings','Pattern matching in market data','Dynamic Programming','LC Phase 1'],
    ['LC','32','Longest Valid Parentheses','','Hard','Stack + DP','Order validation sequences','Dynamic Programming','LC Phase 1'],
    ['LC','42','Trapping Rain Water','','Hard','Two pointer / Stack','Volume accumulation models','Dynamic Programming','LC Phase 1'],
    ['LC','44','Wildcard Matching','','Hard','2D DP','Flexible symbol matching','Dynamic Programming','LC Phase 1'],
    ['LC','72','Edit Distance','','Hard','Classic DP','Signal similarity scoring','Dynamic Programming','LC Phase 1'],
    ['LC','87','Scramble String','','Hard','3D DP / Memo','Permutation analysis','Dynamic Programming','LC Phase 1'],
    ['LC','97','Interleaving String','','Hard','2D DP','Merged stream validation','Dynamic Programming','LC Phase 1'],
    ['LC','115','Distinct Subsequences','','Hard','DP counting','Combinatorial trade counting','Dynamic Programming','LC Phase 1'],
    ['LC','123','Best Time to Buy/Sell Stock III','','Hard','State-machine DP','Directly models trading','Dynamic Programming','LC Phase 1'],
    ['LC','132','Palindrome Partitioning II','','Hard','DP + Manacher','String decomposition','Dynamic Programming','LC Phase 1'],
    ['LC','174','Dungeon Game','','Hard','Reverse DP','Risk-adjusted path finding','Dynamic Programming','LC Phase 1'],
    ['LC','188','Best Time to Buy/Sell Stock IV','','Hard','K-transaction DP','Core HFT portfolio logic','Dynamic Programming','LC Phase 1'],
    ['LC','312','Burst Balloons','','Hard','Interval DP','Optimal order execution','Dynamic Programming','LC Phase 1'],
    ['LC','329','Longest Increasing Path in Matrix','','Hard','DFS + Memo','Trend detection in grids','Dynamic Programming','LC Phase 1'],
    ['LC','354','Russian Doll Envelopes','','Hard','LIS + Binary Search','Nested constraint optimization','Dynamic Programming','LC Phase 1'],
    ['LC','403','Frog Jump','','Hard','DP on states','Discrete price jump models','Dynamic Programming','LC Phase 1'],
    ['LC','410','Split Array Largest Sum','','Hard','Binary Search + DP','Order splitting optimization','Dynamic Programming','LC Phase 1'],
    ['LC','514','Freedom Trail','','Hard','DP on ring','Circular buffer management','Dynamic Programming','LC Phase 1'],
    ['LC','664','Strange Printer','','Hard','Interval DP','Batch execution planning','Dynamic Programming','LC Phase 1'],
    ['LC','691','Stickers to Spell Word','','Hard','Bitmask DP','Combination optimization','Dynamic Programming','LC Phase 1'],
    ['LC','741','Cherry Pickup','','Hard','3D DP','Two-agent optimization','Dynamic Programming','LC Phase 1'],
    ['LC','879','Profitable Schemes','','Hard','Knapsack DP','Portfolio constraint modeling','Dynamic Programming','LC Phase 1'],
    ['LC','1000','Min Cost to Merge Stones','','Hard','Interval DP','Merge cost optimization','Dynamic Programming','LC Phase 1'],
    ['LC','1312','Minimum Insertion Steps to Make String Palindrome','','Hard','Interval DP','String transformation costs','Dynamic Programming','LC Phase 1'],
    ['LC','1547','Minimum Cost to Cut a Stick','','Hard','Interval DP','Optimal segmentation','Dynamic Programming','LC Phase 1'],
    // Category 2: Graphs (20)
    ['LC','127','Word Ladder','','Hard','BFS','State space exploration','Graphs','LC Phase 1'],
    ['LC','212','Word Search II','','Hard','Trie + DFS','Multi-pattern scan','Graphs','LC Phase 1'],
    ['LC','239','Sliding Window Maximum','','Hard','Deque','Rolling max bid/ask','Graphs','LC Phase 1'],
    ['LC','269','Alien Dictionary','','Hard','Topological Sort','Ordering constraints','Graphs','LC Phase 1'],
    ['LC','295','Find Median from Data Stream','','Hard','Two Heaps','Live P&L median','Graphs','LC Phase 1'],
    ['LC','297','Serialize/Deserialize Binary Tree','','Hard','BFS/DFS','State serialization','Graphs','LC Phase 1'],
    ['LC','332','Reconstruct Itinerary','','Hard','Eulerian Path','Order routing','Graphs','LC Phase 1'],
    ['LC','399','Evaluate Division','','Hard','Weighted Union-Find','Ratio arbitrage','Graphs','LC Phase 1'],
    ['LC','407','Trapping Rain Water II','','Hard','3D BFS/Heap','Multi-dim accumulation','Graphs','LC Phase 1'],
    ['LC','460','LFU Cache','','Hard','HashMap + DLL','Cache replacement in feeds','Graphs','LC Phase 1'],
    ['LC','675','Cut Off Trees for Golf Event','','Hard','BFS + Priority Queue','Prioritized path clearing','Graphs','LC Phase 1'],
    ['LC','778','Swim in Rising Water','','Hard','Binary Search + BFS','Threshold path finding','Graphs','LC Phase 1'],
    ['LC','847','Shortest Path Visiting All Nodes','','Hard','BFS + Bitmask','TSP-like routing','Graphs','LC Phase 1'],
    ['LC','1059','All Paths from Source Lead to Destination','','Hard','DFS / Topo Sort','Flow path validation','Graphs','LC Phase 1'],
    ['LC','1192','Critical Connections in a Network','','Hard','Tarjan Bridge','Network robustness','Graphs','LC Phase 1'],
    ['LC','1203','Sort Items by Groups Respecting Dependencies','','Hard','Topological Sort','Dependency scheduling','Graphs','LC Phase 1'],
    ['LC','1345','Jump Game IV','','Hard','BFS','Skip-connection routing','Graphs','LC Phase 1'],
    ['LC','1368','Minimum Cost to Make at Least One Valid Path','','Hard','BFS / Dijkstra','Cost optimization','Graphs','LC Phase 1'],
    ['LC','1489','Find Critical and Pseudo-Critical Edges in MST','','Hard','MST variants','Network edge importance','Graphs','LC Phase 1'],
    ['LC','1579','Remove Max Number of Edges to Keep Graph Fully Traversable','','Hard','Union-Find','Redundancy removal','Graphs','LC Phase 1'],
    // Category 3: Data Structures (20)
    ['LC','218','The Skyline Problem','','Hard','Segment Tree / Heap','Order book shape','Data Structures','LC Phase 1'],
    ['LC','315','Count of Smaller Numbers After Self','','Hard','BIT / Merge Sort','Rank queries on prices','Data Structures','LC Phase 1'],
    ['LC','327','Count of Range Sum','','Hard','Merge Sort / BIT','Profit range queries','Data Structures','LC Phase 1'],
    ['LC','336','Palindrome Pairs','','Hard','Trie','Symmetric signal detection','Data Structures','LC Phase 1'],
    ['LC','352','Data Stream as Disjoint Intervals','','Hard','TreeMap','Price interval tracking','Data Structures','LC Phase 1'],
    ['LC','381','Insert Delete GetRandom O(1) Duplicates allowed','','Hard','HashMap + Vector','Order book data structure','Data Structures','LC Phase 1'],
    ['LC','432','All O(1) Data Structure','','Hard','DLL + HashMap','Frequency tracking feeds','Data Structures','LC Phase 1'],
    ['LC','493','Reverse Pairs','','Hard','Merge Sort / BIT','Inversion counting','Data Structures','LC Phase 1'],
    ['LC','699','Falling Squares','','Hard','Segment Tree','Stacked position tracking','Data Structures','LC Phase 1'],
    ['LC','715','Range Module','','Hard','Segment Tree','Interval management','Data Structures','LC Phase 1'],
    ['LC','732','My Calendar III','','Hard','Segment Tree Lazy','Booking / exposure overlap','Data Structures','LC Phase 1'],
    ['LC','850','Rectangle Area II','','Hard','Coordinate Compress + ST','Area sweep','Data Structures','LC Phase 1'],
    ['LC','1157','Online Majority Element In Subarray','','Hard','Segment Tree + BS','Dominant asset detection','Data Structures','LC Phase 1'],
    ['LC','1649','Create Sorted Array through Instructions','','Hard','BIT','Online insertion rank','Data Structures','LC Phase 1'],
    ['LC','1707','Maximum XOR With an Element From Array','','Hard','Trie offline','Bitwise query answering','Data Structures','LC Phase 1'],
    ['LC','1724','Checking Existence of Edge Length Limited Paths II','','Hard','Union-Find','Connectivity queries','Data Structures','LC Phase 1'],
    ['LC','2013','Detect Squares','','Hard','HashMap counting','2D geometric structures','Data Structures','LC Phase 1'],
    ['LC','2040','Kth Smallest Product of Two Sorted Arrays','','Hard','Binary Search','Order statistics','Data Structures','LC Phase 1'],
    ['LC','2276','Count Integers in Intervals','','Hard','Segment Tree','Interval coverage','Data Structures','LC Phase 1'],
    ['LC','2286','Booking Concert Tickets in Groups','','Hard','Segment Tree','Real-time booking system','Data Structures','LC Phase 1'],
    // Category 4: Math/Prob/Bits (20)
    ['LC','149','Max Points on a Line','','Hard','GCD / Geometry','Collinear price levels','Math & Probability','LC Phase 2'],
    ['LC','166','Fraction to Recurring Decimal','','Hard','Long Division','Exact decimal pricing','Math & Probability','LC Phase 2'],
    ['LC','233','Number of Digit One','','Hard','Math DP','Counting in ranges','Math & Probability','LC Phase 2'],
    ['LC','282','Expression Add Operators','','Hard','DFS + Pruning','Expression evaluation','Math & Probability','LC Phase 2'],
    ['LC','335','Self Crossing','','Hard','Geometry','Path self-intersection','Math & Probability','LC Phase 2'],
    ['LC','458','Poor Pigs','','Hard','Information Theory','Binary search / entropy','Math & Probability','LC Phase 2'],
    ['LC','483','Smallest Good Base','','Hard','Binary Search + Math','Number base encoding','Math & Probability','LC Phase 2'],
    ['LC','517','Super Washing Machines','','Hard','Greedy + Math','Flow balance','Math & Probability','LC Phase 2'],
    ['LC','564','Find the Closest Palindrome','','Hard','Math edge cases','Symmetric pricing','Math & Probability','LC Phase 2'],
    ['LC','587','Erect the Fence','','Hard','Convex Hull','Geometric boundary','Math & Probability','LC Phase 2'],
    ['LC','668','Kth Smallest Number in Multiplication Table','','Hard','Binary Search','Order of magnitude search','Math & Probability','LC Phase 2'],
    ['LC','679','24 Game','','Hard','DFS + Fractions','Classic HFT brain teaser','Math & Probability','LC Phase 2'],
    ['LC','829','Consecutive Numbers Sum','','Hard','Math','Decomposition problems','Math & Probability','LC Phase 2'],
    ['LC','878','Nth Magical Number','','Hard','Binary Search + LCM','Number theory','Math & Probability','LC Phase 2'],
    ['LC','906','Super Palindromes','','Hard','Math + Brute Force','Enumeration with constraints','Math & Probability','LC Phase 2'],
    ['LC','972','Equal Rational Numbers','','Hard','Math parsing','Rational number equality','Math & Probability','LC Phase 2'],
    ['LC','1067','Digit Count in Range','','Hard','Digit DP','Frequency in range','Math & Probability','LC Phase 2'],
    ['LC','1220','Count Vowels Permutation','','Hard','Matrix Exponentiation','Fast sequence counting','Math & Probability','LC Phase 2'],
    ['LC','1330','Reverse Subarray to Maximize Array Value','','Hard','Math greedy','Profit maximization','Math & Probability','LC Phase 2'],
    ['LC','2376','Count Special Integers','','Hard','Digit DP','Constrained counting','Math & Probability','LC Phase 2'],
    // Category 5: Strings (15)
    ['LC','4','Median of Two Sorted Arrays','','Hard','Binary Search','Real-time median pricing','Strings & Sliding Window','LC Phase 1'],
    ['LC','30','Substring with Concatenation of All Words','','Hard','Sliding Window','Multi-signal detection','Strings & Sliding Window','LC Phase 1'],
    ['LC','37','Sudoku Solver','','Hard','Backtracking','Constraint satisfaction','Strings & Sliding Window','LC Phase 1'],
    ['LC','41','First Missing Positive','','Hard','Index hashing','Gap finding in sequences','Strings & Sliding Window','LC Phase 1'],
    ['LC','51','N-Queens','','Hard','Backtracking','Combinatorial constraints','Strings & Sliding Window','LC Phase 1'],
    ['LC','52','N-Queens II','','Hard','Bitmask Backtrack','Optimized enumeration','Strings & Sliding Window','LC Phase 1'],
    ['LC','76','Minimum Window Substring','','Hard','Sliding Window','Minimum coverage queries','Strings & Sliding Window','LC Phase 1'],
    ['LC','84','Largest Rectangle in Histogram','','Hard','Stack','Order book depth','Strings & Sliding Window','LC Phase 1'],
    ['LC','85','Maximal Rectangle','','Hard','Stack + DP','2D order book analysis','Strings & Sliding Window','LC Phase 1'],
    ['LC','214','Shortest Palindrome','','Hard','KMP / Z-function','String preprocessing','Strings & Sliding Window','LC Phase 2'],
    ['LC','466','Count the Repetitions','','Hard','String cycle detection','Period analysis','Strings & Sliding Window','LC Phase 2'],
    ['LC','736','Parse Lisp Expression','','Hard','Recursion + HashMap','Expression interpreter','Strings & Sliding Window','LC Phase 2'],
    ['LC','1163','Last Substring in Lexicographic Order','','Hard','Two pointer','Lexicographic optimization','Strings & Sliding Window','LC Phase 2'],
    ['LC','1178','Number of Valid Words for Each Puzzle','','Hard','Trie + Bitmask','Constraint lookup','Strings & Sliding Window','LC Phase 2'],
    ['LC','1235','Maximum Profit in Job Scheduling','','Hard','DP + Binary Search','Interval scheduling','Strings & Sliding Window','LC Phase 2'],
    // Category 6: Greedy (15)
    ['LC','45','Jump Game II','','Hard','Greedy BFS','Min-hop execution','Greedy & Intervals','LC Phase 1'],
    ['LC','135','Candy','','Hard','Two-pass Greedy','Incentive distribution','Greedy & Intervals','LC Phase 1'],
    ['LC','316','Remove Duplicate Letters','','Hard','Monotonic Stack','Lexicographic greedy','Greedy & Intervals','LC Phase 1'],
    ['LC','330','Patching Array','','Hard','Greedy','Coverage gap filling','Greedy & Intervals','LC Phase 1'],
    ['LC','358','Rearrange String k Distance Apart','','Hard','Greedy + Heap','Spacing constraints','Greedy & Intervals','LC Phase 1'],
    ['LC','420','Strong Password Checker','','Hard','Greedy + Cases','Rule-based compliance','Greedy & Intervals','LC Phase 1'],
    ['LC','502','IPO','','Hard','Two Heaps + Greedy','Capital allocation','Greedy & Intervals','LC Phase 1'],
    ['LC','630','Course Schedule III','','Hard','Greedy + Heap','Deadline scheduling','Greedy & Intervals','LC Phase 1'],
    ['LC','759','Employee Free Time','','Hard','Interval Merge','Availability windows','Greedy & Intervals','LC Phase 1'],
    ['LC','857','Minimum Cost to Hire K Workers','','Hard','Fractional greedy','Workforce cost optimization','Greedy & Intervals','LC Phase 2'],
    ['LC','871','Minimum Number of Refueling Stops','','Hard','Greedy + Heap','Threshold-based routing','Greedy & Intervals','LC Phase 2'],
    ['LC','1040','Moving Stones Until Consecutive II','','Hard','Sliding Window','Position optimization','Greedy & Intervals','LC Phase 2'],
    ['LC','1326','Minimum Number of Taps to Open to Water a Garden','','Hard','Greedy / DP','Coverage with fewest actions','Greedy & Intervals','LC Phase 2'],
    ['LC','1383','Maximum Performance of a Team','','Hard','Greedy + Heap','Team/portfolio selection','Greedy & Intervals','LC Phase 2'],
    ['LC','1675','Minimize Deviation in Array','','Hard','Greedy + TreeSet','Min-max range problems','Greedy & Intervals','LC Phase 2'],
    // Category 7: Game Theory (20)
    ['LC','375','Guess Number Higher or Lower II','','Hard','MiniMax DP','Game tree / adversarial','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','486','Predict the Winner','','Hard','MiniMax DP','Zero-sum game theory','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','546','Remove Boxes','','Hard','3D Interval DP','Grouping optimization','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','552','Student Attendance Record II','','Hard','DP states','Sequence counting','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','600','Non-negative Integers without Consecutive Ones','','Hard','Digit DP','Constrained counting','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','629','K Inverse Pairs Array','','Hard','DP + Prefix Sum','Permutation counting','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','761','Special Binary String','','Hard','Greedy + Recursion','Balanced partitioning','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','913','Cat and Mouse','','Hard','MiniMax + BFS','Two-player zero-sum','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','975','Odd Even Jump','','Hard','Monotonic Stack + DP','Conditional jumps','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1066','Campus Bikes II','','Hard','Bitmask DP','Assignment optimization','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1125','Smallest Sufficient Team','','Hard','Bitmask DP','Minimum coverage','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1223','Dice Roll Simulation','','Hard','DP with constraint','Constrained enumeration','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1259','Handshakes That Do Not Cross','','Hard','Catalan DP','Combinatorial counting','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1340','Jump Game V','','Hard','DP + sorted order','Jump constraint modeling','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1349','Maximum Students Taking Exam','','Hard','Bitmask DP','Constraint satisfaction','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1406','Stone Game III','','Hard','Game DP','Optimal play strategies','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1444','Number of Ways of Cutting a Pizza','','Hard','DP + prefix sum','Resource division','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1531','String Compression II','','Hard','DP + k deletions','Compression under constraints','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1553','Minimum Number of Days to Eat N Oranges','','Hard','Memoized DP','Multi-path optimization','Game Theory & Brain Teasers','LC Phase 2'],
    ['LC','1681','Minimum Incompatibility','','Hard','Bitmask DP','Portfolio grouping','Game Theory & Brain Teasers','LC Phase 2'],
    // Category 8: Expert (15)
    ['LC','23','Merge k Sorted Lists','','Hard','Priority Queue','Order book merging','Expert Level','LC Phase 3'],
    ['LC','128','Longest Consecutive Sequence','','Hard','Hash Set','Streak detection in ticks','Expert Level','LC Phase 3'],
    ['LC','140','Word Break II','','Hard','DFS + Memo','Signal decomposition','Expert Level','LC Phase 3'],
    ['LC','1269','Number of Ways to Stay in the Same Place After Some Steps','','Hard','DP','Position-bounded walks','Expert Level','LC Phase 3'],
    ['LC','1411','Number of Ways to Paint N × 3 Grid','','Hard','State DP','Coloring constraints','Expert Level','LC Phase 3'],
    ['LC','1434','Number of Ways to Wear Different Hats','','Hard','Bitmask DP','Assignment problems','Expert Level','LC Phase 3'],
    ['LC','1473','Paint House III','','Hard','3D DP','Multi-constraint coloring','Expert Level','LC Phase 3'],
    ['LC','1499','Max Value of Equation','','Hard','Sliding Window + Heap','Price-based optimization','Expert Level','LC Phase 3'],
    ['LC','1569','Number of Ways to Reorder Array to Get Same BST','','Hard','Divide & Conquer DP','Tree arrangement counting','Expert Level','LC Phase 3'],
    ['LC','1617','Count Subtrees With Max Distance Between Cities','','Hard','Bitmask + Dijkstra','Subgraph metric analysis','Expert Level','LC Phase 3'],
    ['LC','1751','Maximum Number of Events That Can Be Attended II','','Hard','DP + Binary Search','Event scheduling','Expert Level','LC Phase 3'],
    ['LC','1787','Make the XOR of All Segments Equal to Zero','','Hard','Bit manipulation','Bitwise equality constraints','Expert Level','LC Phase 3'],
    ['LC','1808','Maximize Number of Nice Divisors','','Hard','Math + Fast Exp','Number theory optimization','Expert Level','LC Phase 3'],
    ['LC','218','The Skyline Problem (Expert Review)','','Hard','Segment Tree','Advanced order book shape','Expert Level','LC Phase 3'],
    ['LC','297','Serialize and Deserialize Binary Tree (Expert)','','Hard','BFS/DFS advanced','Advanced state serialization','Expert Level','LC Phase 3'],
  ];

  const cfProblems = [
    // Phase A
    ['CF','1033C','Checkpoints','Codeforces Round 500 (Div. 1, based on Div. 2)','1600','Greedy with conditions','','Greedy & Sorting','Phase A'],
    ['CF','1077C','Good Array','Codeforces Round 523 (Div. 2)','1600','Sorting + greedy','','Greedy & Sorting','Phase A'],
    ['CF','1196C','Robot Breakout','Codeforces Round 572 (Div. 2)','1600','Greedy range intersection','','Greedy & Sorting','Phase A'],
    ['CF','1208D','Restore Permutation','Codeforces Round 580 (Div. 2)','1700','Greedy + Fenwick tree','','Greedy & Sorting','Phase A'],
    ['CF','1285C','Fadi and LCM','Codeforces Round 612 (Div. 2)','1600','Greedy + factorization','','Greedy & Sorting','Phase A'],
    ['CF','1324D','Pair of Topics','Codeforces Round 628 (Div. 2)','1600','Sorting + binary search','','Greedy & Sorting','Phase A'],
    ['CF','1360E','Polygon Embedding','Codeforces Round 646 (Div. 2)','1600','Sorting','','Greedy & Sorting','Phase A'],
    ['CF','1399C','Boats Competition','Codeforces Round 667 (Div. 2)','1500','Two pointers + sorting','','Greedy & Sorting','Phase A'],
    ['CF','1406B','Maximum Product','Codeforces Round 668 (Div. 2)','1400','Greedy sorting','','Greedy & Sorting','Phase A'],
    ['CF','1430C','Numbers on Whiteboard','Codeforces Round 677 (Div. 2)','1500','Greedy simulation','','Greedy & Sorting','Phase A'],
    ['CF','1118D','Coffee and Coursework','Codeforces Round 540 (Div. 3)','1700','Binary search on answer','','Binary Search','Phase A'],
    ['CF','1300C','Anu has a Function','Codeforces Round 621 (Div. 1)','1700','Bit manipulation','','Binary Search','Phase A'],
    ['CF','1328C','Ternary XOR','Codeforces Round 629 (Div. 3)','1700','Greedy on bits','','Binary Search','Phase A'],
    ['CF','1399D','Binary String to Subsequences','Codeforces Round 667 (Div. 2)','1700','Greedy queues','','Binary Search','Phase A'],
    ['CF','1404C','Fixed Point Removal','Codeforces Round 668 (Div. 2)','1800','Binary search on segments','','Binary Search','Phase A'],
    ['CF','1430D','String Deletion','Codeforces Round 677 (Div. 2)','1700','Greedy two pointer','','Binary Search','Phase A'],
    ['CF','1462D','Add to Neighbour and Remove','Codeforces Round 693 (Div. 3)','1700','Binary search','','Binary Search','Phase A'],
    ['CF','1490D','Permutation Transformation','Codeforces Round 704 (Div. 2)','1700','Recursive + greedy','','Binary Search','Phase A'],
    ['CF','1512D','Corrupted Array','Codeforces Round 717 (Div. 2)','1700','Binary search + greedy','','Binary Search','Phase A'],
    ['CF','1535C','Unstable String','Codeforces Round 727 (Div. 2)','1600','Greedy simulation','','Binary Search','Phase A'],
    ['CF','1083D','The Fair Nut','Codeforces Round 523 (Div. 1)','1700','DP on array','','DP Basic','Phase A'],
    ['CF','1102D','Balanced Ternary String','Codeforces Round 530 (Div. 2)','1600','DP / Greedy','','DP Basic','Phase A'],
    ['CF','1144D','Equalize Them All','Codeforces Round 547 (Div. 3)','1700','DP on groups','','DP Basic','Phase A'],
    ['CF','1175D','Array Splitting','Codeforces Round 562 (Div. 2)','1700','DP with sorting','','DP Basic','Phase A'],
    ['CF','1197D','Yet Another Subarray Problem','Codeforces Round 573 (Div. 2)','1700','DP with prefix','','DP Basic','Phase A'],
    ['CF','1217D','Coloring Edges','Codeforces Round 585 (Div. 2)','1700','Graph + DP','','DP Basic','Phase A'],
    ['CF','1272D','Remove One Element','Codeforces Round 605 (Div. 3)','1700','DP prefix/suffix','','DP Basic','Phase A'],
    ['CF','1301C','Ayoub and Lost Array','Codeforces Round 620 (Div. 2)','1600','DP counting','','DP Basic','Phase A'],
    ['CF','1374D','Zero-One Matrix','Codeforces Round 651 (Div. 2)','1700','BFS shortest dist','','DP Basic','Phase A'],
    ['CF','1436C','Binary Search','Codeforces Round 679 (Div. 2)','1700','Simulation','','DP Basic','Phase A'],
    ['CF','1037D','Valid BFS?','Codeforces Round 504 (Div. 1, based on Div. 2)','1700','BFS tree validation','','Graphs BFS/DFS','Phase A'],
    ['CF','1076D','Edge Deletion','Codeforces Round 521 (Div. 3)','1700','Dijkstra pruning','','Graphs BFS/DFS','Phase A'],
    ['CF','1106D','Lunar New Year and Paths','Codeforces Round 534 (Div. 2)','1700','DFS + DSU','','Graphs BFS/DFS','Phase A'],
    ['CF','1151D','Stas and the Queue','Codeforces Round 553 (Div. 2)','1700','Segment tree','','Graphs BFS/DFS','Phase A'],
    ['CF','1153D','Rectangle Painting 1','Codeforces Round 554 (Div. 2)','1700','Prefix sum 2D','','Graphs BFS/DFS','Phase A'],
    ['CF','1154D','Walking Robot','Codeforces Round 554 (Div. 1)','1700','Greedy on graph','','Graphs BFS/DFS','Phase A'],
    ['CF','1256D','Binary String Minimizing','Codeforces Round 595 (Div. 3)','1600','Greedy','','Graphs BFS/DFS','Phase A'],
    ['CF','1283D','Christmas Trees','Codeforces Round 608 (Div. 3)','1700','BFS + prefix','','Graphs BFS/DFS','Phase A'],
    ['CF','1303D','Fill the Grid','Codeforces Round 618 (Div. 2)','1700','Greedy + prefix','','Graphs BFS/DFS','Phase A'],
    ['CF','1385D','a-Good String','Codeforces Round 657 (Div. 2)','1700','Divide and conquer','','Graphs BFS/DFS','Phase A'],
    ['CF','1105C','Ayoub and XOR','Codeforces Round 533 (Div. 2)','1700','XOR + Math','','Math & Number Theory','Phase A'],
    ['CF','1114C','Trailing Loves','Codeforces Round 538 (Div. 2)','1600','Prime factorization','','Math & Number Theory','Phase A'],
    ['CF','1165D','Almost All Divisors','Codeforces Round 559 (Div. 2)','1600','Factorization','','Math & Number Theory','Phase A'],
    ['CF','1180C','Valeriy and Deque','Codeforces Round 563 (Div. 2)','1700','Deque simulation','','Math & Number Theory','Phase A'],
    ['CF','1188C','Array Beauty','Codeforces Round 571 (Div. 2)','1700','Binary search + counting','','Math & Number Theory','Phase A'],
    ['CF','1200D','White Lines','Codeforces Round 577 (Div. 2)','1800','Prefix sum sliding window','','Math & Number Theory','Phase A'],
    ['CF','1220D','Alex and Julian','Codeforces Round 587 (Div. 3)','1600','Math parity','','Math & Number Theory','Phase A'],
    ['CF','1295D','Same GCDs','Codeforces Round 615 (Div. 3)','1700','Euler totient','','Math & Number Theory','Phase A'],
    ['CF','1311D','Three Numbers','Codeforces Round 622 (Div. 2)','1700','Math + prime factorization','','Math & Number Theory','Phase A'],
    ['CF','1358D','The Bakery','Educational Codeforces Round 83','1800','DP + segment tree','','Math & Number Theory','Phase A'],
    ['CF','1234D','Distinct Characters Queries','Codeforces Round 589 (Div. 2)','1700','Sorted set queries','','Data Structures Intro','Phase A'],
    ['CF','1249D','Too Many Segments','Codeforces Round 596 (Div. 2)','1800','Set + greedy','','Data Structures Intro','Phase A'],
    ['CF','1253D','Harmonious Graph','Codeforces Round 597 (Div. 2)','1700','DSU','','Data Structures Intro','Phase A'],
    ['CF','1264D','Beautiful Bracket Sequence','Codeforces Round 600 (Div. 2)','1800','Combinatorics','','Data Structures Intro','Phase A'],
    ['CF','1209G','Into Blocks','Codeforces Round 582 (Div. 2)','1800','DP + DSU','','Data Structures Intro','Phase A'],
    ['CF','1156D','0-1-2 MST','Codeforces Round 555 (Div. 3)','1700','DSU + DP','','Data Structures Intro','Phase A'],
    ['CF','1131D','Gourmet Choice','Codeforces Round 540 (Div. 2)','1800','DSU + topo sort','','Data Structures Intro','Phase A'],
    ['CF','1132D','Stressful Training','Codeforces Round 541 (Div. 2)','1800','Greedy + heap','','Data Structures Intro','Phase A'],
    ['CF','1260D','A Game with Traps','Codeforces Round 601 (Div. 2)','1700','Bitmask + math','','Data Structures Intro','Phase A'],
    ['CF','1375E','Ugly Pairs','Codeforces Round 652 (Div. 2)','1900','Parity + sorting','','Data Structures Intro','Phase A'],
    ['CF','1335D','Anti-Sudoku','Codeforces Round 632 (Div. 2)','1600','Construction','','Mixed 1700-1800','Phase A'],
    ['CF','1354C','Simple Polygon Embedding','Codeforces Round 644 (Div. 3)','1600','Greedy geometry','','Mixed 1700-1800','Phase A'],
    ['CF','1370C','Number Game','Codeforces Round 649 (Div. 2)','1700','Game simulation','','Mixed 1700-1800','Phase A'],
    ['CF','1373D','Maximum Sum on Even Positions','Codeforces Round 649 (Div. 2)','1600','Greedy sorting pairs','','Mixed 1700-1800','Phase A'],
    ['CF','1379C','Choosing Flowers','Codeforces Round 654 (Div. 2)','1800','Sorting + prefix sum','','Mixed 1700-1800','Phase A'],
    ['CF','1388C','Uncle Bogdan and Country Road','Codeforces Round 660 (Div. 2)','1800','Geometry + sorting','','Mixed 1700-1800','Phase A'],
    ['CF','1396C','Monster Invaders','Codeforces Round 663 (Div. 2)','1700','DP on cycle','','Mixed 1700-1800','Phase A'],
    ['CF','1401D','Maximum Distributed Tree','Codeforces Round 664 (Div. 2)','1800','Greedy on tree','','Mixed 1700-1800','Phase A'],
    ['CF','1421D','Hexagons','Codeforces Round 674 (Div. 2)','1800','Shortest path on grid','','Mixed 1700-1800','Phase A'],
    ['CF','1426D','Non-zero Segments','Codeforces Round 675 (Div. 2)','1700','Prefix sums','','Mixed 1700-1800','Phase A'],
    // Phase B
    ['CF','1076E','Vasya and Book','Codeforces Round 521 (Div. 3)','1900','DP on segments','','Advanced DP','Phase B'],
    ['CF','1093F','Vasya and Array','Codeforces Round 524 (Div. 2)','1900','DP grid','','Advanced DP','Phase B'],
    ['CF','1148H','Holy Doughnut','Codeforces Round 550 (Div. 3)','1900','DP on cycle','','Advanced DP','Phase B'],
    ['CF','1167E','Range Deleting','Codeforces Round 560 (Div. 2)','2000','Two pointer + suffix DP','','Advanced DP','Phase B'],
    ['CF','1173E','Nauuo and Pictures','Codeforces Round 561 (Div. 2)','2000','DP + probability','','Advanced DP','Phase B'],
    ['CF','1182D','Complete Mirror','Codeforces Round 566 (Div. 2)','2000','Tree DP','','Advanced DP','Phase B'],
    ['CF','1185G','Playlist','Codeforces Round 567 (Div. 2)','2000','Segment tree DP','','Advanced DP','Phase B'],
    ['CF','1199D','Welfare State','Codeforces Round 575 (Div. 2)','1900','Suffix max + updates','','Advanced DP','Phase B'],
    ['CF','1217E','Kronecker Theorem','Codeforces Round 585 (Div. 2)','2000','Number theory + sets','','Advanced DP','Phase B'],
    ['CF','1242D','Number Discovery','Codeforces Round 590 (Div. 3)','1900','DP counting','','Advanced DP','Phase B'],
    ['CF','1092F','Tree with Maximum Cost','Codeforces Round 523 (Div. 2)','1900','Tree DP re-rooting','','Trees LCA/Euler','Phase B'],
    ['CF','1187E','Tree Painting','Codeforces Round 569 (Div. 2)','2000','Tree DP / DFS','','Trees LCA/Euler','Phase B'],
    ['CF','1195E','Number of Ways','Codeforces Round 572 (Div. 2)','1900','Prefix sum + conditions','','Trees LCA/Euler','Phase B'],
    ['CF','1214E','Petya and Construction Set','Codeforces Round 583 (Div. 1)','1900','Tree construction','','Trees LCA/Euler','Phase B'],
    ['CF','1228D','Complete Tripartite','Codeforces Round 586 (Div. 2)','1900','Graph partition','','Trees LCA/Euler','Phase B'],
    ['CF','1239C','Queue in the Bank','Codeforces Round 591 (Div. 2)','1900','Simulation','','Trees LCA/Euler','Phase B'],
    ['CF','1294D','MEX Maximizing','Codeforces Round 614 (Div. 1)','1900','Greedy + sets','','Trees LCA/Euler','Phase B'],
    ['CF','1307D','Cow and Fields','Codeforces Round 621 (Div. 2)','1900','Tree + LCA','','Trees LCA/Euler','Phase B'],
    ['CF','1406C','Link Cut Centroids','Codeforces Round 668 (Div. 2)','1900','Tree centroid','','Trees LCA/Euler','Phase B'],
    ['CF','1444C','Short Program','Codeforces Round 682 (Div. 2)','2000','Bitwise construction','','Trees LCA/Euler','Phase B'],
    ['CF','1234E','Special Permutations','Codeforces Round 589 (Div. 2)','1900','Counting + segment tree','','Segment Tree & BIT','Phase B'],
    ['CF','1258D','Count Sums','Codeforces Round 599 (Div. 2)','2000','BIT + offline','','Segment Tree & BIT','Phase B'],
    ['CF','1266E','Spaceship Glitching','Codeforces Round 601 (Div. 1)','2000','XOR + segment tree','','Segment Tree & BIT','Phase B'],
    ['CF','1285D','Dr. Evil Underscores','Codeforces Round 612 (Div. 2)','1900','Divide & conquer XOR','','Segment Tree & BIT','Phase B'],
    ['CF','1296E','String Coloring','Codeforces Round 614 (Div. 2)','1900','Greedy + bipartite','','Segment Tree & BIT','Phase B'],
    ['CF','1312E','Array Shrinking','Codeforces Round 623 (Div. 2)','2000','DP + segment tree','','Segment Tree & BIT','Phase B'],
    ['CF','1326E','Bombs','Codeforces Round 629 (Div. 1)','2000','Binary search + seg tree','','Segment Tree & BIT','Phase B'],
    ['CF','1334E','Divisor Trick','Codeforces Round 633 (Div. 2)','1900','Number theory','','Segment Tree & BIT','Phase B'],
    ['CF','1342E','Placing Rooks','Codeforces Round 636 (Div. 2)','2000','Inclusion-exclusion','','Segment Tree & BIT','Phase B'],
    ['CF','1380D','Lucky Permutation','Codeforces Round 655 (Div. 2)','2000','DSU + counting','','Segment Tree & BIT','Phase B'],
    ['CF','1348D','Phoenix and Science','Codeforces Round 641 (Div. 2)','1900','Math + invariant','','Combinatorics & NT','Phase B'],
    ['CF','1359E','Modular Stability','Codeforces Round 645 (Div. 2)','1900','Number theory + counting','','Combinatorics & NT','Phase B'],
    ['CF','1370E','Binary Subsequences','Codeforces Round 649 (Div. 2)','1900','Greedy','','Combinatorics & NT','Phase B'],
    ['CF','1399E','Weights Division','Codeforces Round 667 (Div. 2)','1900','Tree + greedy','','Combinatorics & NT','Phase B'],
    ['CF','1408D','Productivity','Codeforces Round 670 (Div. 2)','1900','Binary search','','Combinatorics & NT','Phase B'],
    ['CF','1418D','Buying Laptops','Codeforces Round 672 (Div. 2)','1900','Prefix sums','','Combinatorics & NT','Phase B'],
    ['CF','1420D','Rescue Nibel','Codeforces Round 674 (Div. 2)','1900','Combinatorics','','Combinatorics & NT','Phase B'],
    ['CF','1422D','Returning Home','Codeforces Round 674 (Div. 2)','1900','Dijkstra + virtual node','','Combinatorics & NT','Phase B'],
    ['CF','1462E','Close Tuples','Codeforces Round 693 (Div. 3)','1900','Combinatorics','','Combinatorics & NT','Phase B'],
    ['CF','1499D','The Number of Pairs','Codeforces Round 711 (Div. 2)','1900','Math + Euler totient','','Combinatorics & NT','Phase B'],
    ['CF','1321D','Navigation System','Codeforces Round 627 (Div. 2)','1900','Dijkstra','','Graph Dijkstra/SCC','Phase B'],
    ['CF','1390E','Dreabeats','Codeforces Round 662 (Div. 2)','2000','Graph + math','','Graph Dijkstra/SCC','Phase B'],
    ['CF','1395C','Omkar and Waterslide','Codeforces Round 663 (Div. 2)','1900','Graph invariants','','Graph Dijkstra/SCC','Phase B'],
    ['CF','1430E','String Reversal','Codeforces Round 677 (Div. 2)','2000','Permutation + BIT','','Graph Dijkstra/SCC','Phase B'],
    ['CF','1442D','Extreme Subtraction','Codeforces Round 682 (Div. 2)','2000','Prefix/suffix min','','Graph Dijkstra/SCC','Phase B'],
    ['CF','1452D','Radio Towers','Codeforces Round 686 (Div. 2)','1900','DP + prefix','','Graph Dijkstra/SCC','Phase B'],
    ['CF','1476D','Journey','Codeforces Round 697 (Div. 2)','1900','DP on tree','','Graph Dijkstra/SCC','Phase B'],
    ['CF','1481D','AB Graph','Codeforces Round 699 (Div. 2)','1900','Graph analysis','','Graph Dijkstra/SCC','Phase B'],
    ['CF','1494D','Dogeforces','Codeforces Round 706 (Div. 2)','1900','Tree DFS','','Graph Dijkstra/SCC','Phase B'],
    ['CF','1511D','Min Cost String','Codeforces Round 717 (Div. 2)','2000','Eulerian path + DFS','','Graph Dijkstra/SCC','Phase B'],
    ['CF','1175F','Subpermutations','Codeforces Round 562 (Div. 1)','1900','Hashing','','String Algorithms','Phase B'],
    ['CF','1409D','Decrease the Sum of Digits','Codeforces Round 671 (Div. 2)','1900','Greedy + carry','','String Algorithms','Phase B'],
    ['CF','1444D','Rectangular Deletion','Codeforces Round 682 (Div. 2)','2000','2D prefix','','String Algorithms','Phase B'],
    ['CF','1446D','Frequency of Ringing','Codeforces Round 683 (Div. 2)','1900','LCM + range','','String Algorithms','Phase B'],
    ['CF','1468D','Fiend with Kekis','Codeforces Round 695 (Div. 2)','1900','DP on positions','','String Algorithms','Phase B'],
    ['CF','1471D','Strange Definition','Codeforces Round 696 (Div. 2)','1900','Sieve of Eratosthenes','','String Algorithms','Phase B'],
    ['CF','1485D','Multiples and Power Differences','Codeforces Round 700 (Div. 2)','2000','Greedy + coloring','','String Algorithms','Phase B'],
    ['CF','1490G','Old Floppy Drive','Codeforces Round 704 (Div. 2)','2000','Prefix sum + binary search','','String Algorithms','Phase B'],
    ['CF','1492D','Genius Gambit','Codeforces Round 705 (Div. 2)','2000','Greedy + set','','String Algorithms','Phase B'],
    ['CF','1503D','Flip the Cards','Codeforces Round 712 (Div. 2)','2000','Stack + greedy','','String Algorithms','Phase B'],
    ['CF','1213G','Distinctification','Codeforces Round 583 (Div. 1)','2000','DSU on tree','','Mixed 1900-2000','Phase B'],
    ['CF','1247D','Power Products','Codeforces Round 594 (Div. 2)','1900','Hashing + math','','Mixed 1900-2000','Phase B'],
    ['CF','1297D','About Grisha','Codeforces Round 616 (Div. 2)','1900','Combinatorics','','Mixed 1900-2000','Phase B'],
    ['CF','1363D','Guess The Maximums','Codeforces Round 647 (Div. 2)','1900','Intervals + sets','','Mixed 1900-2000','Phase B'],
    ['CF','1392G','Omkar and Pawn Stars','Codeforces Round 661 (Div. 2)','2000','Greedy + math','','Mixed 1900-2000','Phase B'],
    ['CF','1439C','Engineer Artem','Codeforces Round 681 (Div. 2)','1900','Checkerboard parity','','Mixed 1900-2000','Phase B'],
    ['CF','1455D','Sequence of Actions','Codeforces Round 688 (Div. 2)','1900','Greedy','','Mixed 1900-2000','Phase B'],
    ['CF','1487D','Pythagorean Triples','Codeforces Round 702 (Div. 2)','1900','Math','','Mixed 1900-2000','Phase B'],
    ['CF','1500C','Sum of Cubes','Codeforces Round 711 (Div. 2)','1800','Math cuberoot','','Mixed 1900-2000','Phase B'],
    ['CF','1517D','Explorer Space','Codeforces Round 718 (Div. 2)','2000','DP on tree','','Mixed 1900-2000','Phase B'],
    ['CF','1521D','Nastia and Permutation','Codeforces Round 721 (Div. 2)','1900','Greedy + construction','','Mixed 1900-2000','Phase B'],
    ['CF','1527D','MEX Tree','Codeforces Round 723 (Div. 2)','2000','Tree DSU','','Mixed 1900-2000','Phase B'],
    ['CF','1534D','Lost Array','Codeforces Round 727 (Div. 2)','1900','XOR + math','','Mixed 1900-2000','Phase B'],
    ['CF','1542D','Priority Queue','Codeforces Round 730 (Div. 2)','1900','Simulation','','Mixed 1900-2000','Phase B'],
    ['CF','1545D','Infinite Set','Codeforces Round 731 (Div. 2)','1900','DP + BFS','','Mixed 1900-2000','Phase B'],
    ['CF','1548D','Gregor and Two Painters','Codeforces Round 732 (Div. 2)','2000','Combinatorics','','Mixed 1900-2000','Phase B'],
    ['CF','1553D','Domination','Codeforces Round 736 (Div. 2)','2000','Segment tree','','Mixed 1900-2000','Phase B'],
    ['CF','1559D','Mocha and Diana','Codeforces Round 739 (Div. 2)','2000','DSU + binary search','','Mixed 1900-2000','Phase B'],
    ['CF','1567C','Carrying Conundrum','Codeforces Round 744 (Div. 3)','1900','Math','','Mixed 1900-2000','Phase B'],
    ['CF','1572D','Minimization','Codeforces Round 744 (Div. 3)','1900','DP + prefix','','Mixed 1900-2000','Phase B'],
    // Phase C
    ['CF','1515F','Phoenix and Earthquake','Codeforces Round 718 (Div. 1)','2100','DSU + merge','','Advanced Data Structures','Phase C'],
    ['CF','1516D','Cut','Codeforces Round 719 (Div. 1)','2100','Persistent segment tree','','Advanced Data Structures','Phase C'],
    ['CF','1527E','Partition Equal Pairs','Codeforces Round 723 (Div. 1)','2100','Matching','','Advanced Data Structures','Phase C'],
    ['CF','1528D','Its a Tree','Codeforces Round 724 (Div. 1)','2000','Segment tree beats','','Advanced Data Structures','Phase C'],
    ['CF','1539D','PriceFixed','Codeforces Round 728 (Div. 2)','2100','Two pointer + BIT','','Advanced Data Structures','Phase C'],
    ['CF','1544D','Move and Swap','Codeforces Round 731 (Div. 1)','2100','DP + sorted structures','','Advanced Data Structures','Phase C'],
    ['CF','1553E','Permutation Shift','Codeforces Round 736 (Div. 1)','2100','Permutation cycles','','Advanced Data Structures','Phase C'],
    ['CF','1555D','Say No to Palindromes','Codeforces Round 738 (Div. 2)','2000','Prefix sum + greedy','','Advanced Data Structures','Phase C'],
    ['CF','1556D','Take a Guess','Codeforces Round 739 (Div. 1)','2100','XOR + AND properties','','Advanced Data Structures','Phase C'],
    ['CF','1558D','Top-Notch Insertions','Codeforces Round 740 (Div. 2)','2000','Greedy counting','','Advanced Data Structures','Phase C'],
    ['CF','1562D','Two Hundred Twenty One','Codeforces Round 742 (Div. 2)','2100','Prefix alternating sum','','Advanced Graph & Tree','Phase C'],
    ['CF','1567D','Expression Evaluation Error','Codeforces Round 743 (Div. 2)','2000','Greedy construction','','Advanced Graph & Tree','Phase C'],
    ['CF','1575D','Divisibility','Codeforces Round 746 (Div. 2)','2100','Math recursion','','Advanced Graph & Tree','Phase C'],
    ['CF','1579D','Productive Meeting','Codeforces Round 748 (Div. 2)','2100','Greedy + heap','','Advanced Graph & Tree','Phase C'],
    ['CF','1582D','Vupsen and Pupsen','Codeforces Round 749 (Div. 2)','2000','Graph + tree','','Advanced Graph & Tree','Phase C'],
    ['CF','1594D','The Number of Imposters','Codeforces Round 754 (Div. 2)','2000','Graph bipartite','','Advanced Graph & Tree','Phase C'],
    ['CF','1600D','Painting the Array','Codeforces Round 758 (Div. 2)','2000','Greedy','','Advanced Graph & Tree','Phase C'],
    ['CF','1604D','Beautiful Bouquet','Codeforces Round 759 (Div. 2)','2000','Modular arithmetic','','Advanced Graph & Tree','Phase C'],
    ['CF','1613D','MEX Sequences','Codeforces Round 763 (Div. 2)','2100','Sets + greedy','','Advanced Graph & Tree','Phase C'],
    ['CF','1619D','Cave Exploration','Codeforces Round 766 (Div. 2)','2000','DFS + greedy','','Advanced Graph & Tree','Phase C'],
    ['CF','1625D','K-Fair Tree','Codeforces Round 769 (Div. 2)','2100','Tree divisibility','','Divide Conquer Sweep','Phase C'],
    ['CF','1634D','Finding Zero','Codeforces Round 774 (Div. 2)','2100','Interactive + query','','Divide Conquer Sweep','Phase C'],
    ['CF','1637D','Yet Another Minimization Problem','Codeforces Round 775 (Div. 2)','2100','Mos algorithm','','Divide Conquer Sweep','Phase C'],
    ['CF','1651D','Nearest Excluded Points','Codeforces Round 780 (Div. 2)','2100','BFS + sets','','Divide Conquer Sweep','Phase C'],
    ['CF','1659D','Jumping Grasshopper','Codeforces Round 782 (Div. 2)','2100','Monotonic stack','','Divide Conquer Sweep','Phase C'],
    ['CF','1671D','Insert a Progression','Codeforces Round 787 (Div. 2)','2100','Case analysis','','Divide Conquer Sweep','Phase C'],
    ['CF','1672D','Mathematical Circus','Codeforces Round 788 (Div. 2)','2000','Brute force + constraints','','Divide Conquer Sweep','Phase C'],
    ['CF','1675D','Factorial Divisibility','Codeforces Round 789 (Div. 2)','2100','Number theory','','Divide Conquer Sweep','Phase C'],
    ['CF','1686D','Linguistics','Codeforces Round 795 (Div. 2)','2100','Parsing + greedy','','Divide Conquer Sweep','Phase C'],
    ['CF','1696D','Permutation Graph','Codeforces Round 800 (Div. 2)','2100','Divide and conquer','','Divide Conquer Sweep','Phase C'],
    ['CF','1694D','The Equivalent','Codeforces Round 799 (Div. 2)','2100','DP','','Advanced Trees HLD','Phase C'],
    ['CF','1699D','Almost Triple Deletions','Codeforces Round 803 (Div. 2)','2100','DP + suffix','','Advanced Trees HLD','Phase C'],
    ['CF','1705D','Candy Bags','Codeforces Round 807 (Div. 2)','2100','Greedy + math','','Advanced Trees HLD','Phase C'],
    ['CF','1709D','Ants','Codeforces Round 809 (Div. 2)','2100','Game theory','','Advanced Trees HLD','Phase C'],
    ['CF','1717D','Madoka Corruption Scheme','Codeforces Round 814 (Div. 2)','2100','Combinatorics','','Advanced Trees HLD','Phase C'],
    ['CF','1726D','Edge Deletion','Codeforces Round 818 (Div. 2)','2100','Dijkstra + counting','','Advanced Trees HLD','Phase C'],
    ['CF','1731D','Valiants New Map','Codeforces Round 820 (Div. 2)','2100','Binary search + 2D prefix','','Advanced Trees HLD','Phase C'],
    ['CF','1736D','Equal Binary Subsequences','Codeforces Round 822 (Div. 2)','2100','Greedy + XOR','','Advanced Trees HLD','Phase C'],
    ['CF','1741D','Masha and Beautiful Tree','Codeforces Round 824 (Div. 2)','2000','Segment tree + merging','','Advanced Trees HLD','Phase C'],
    ['CF','1744D','Divisor Chain','Codeforces Round 826 (Div. 2)','2100','Bit manipulation','','Advanced Trees HLD','Phase C'],
    ['CF','1749D','Counting Arrays','Codeforces Round 830 (Div. 2)','2100','Combinatorics','','Misc 2000-2100','Phase C'],
    ['CF','1753D','Valiants Game','Codeforces Round 832 (Div. 2)','2100','Game theory','','Misc 2000-2100','Phase C'],
    ['CF','1760D','Challenging Valleys','Codeforces Round 836 (Div. 2)','2100','Case analysis','','Misc 2000-2100','Phase C'],
    ['CF','1765D','Broken Keyboard','Codeforces Round 839 (Div. 2)','2100','Segment tree','','Misc 2000-2100','Phase C'],
    ['CF','1766D','Lucky Mask','Codeforces Round 840 (Div. 2)','2100','Digit DP','','Misc 2000-2100','Phase C'],
    ['CF','1774D','Flexible String','Codeforces Round 843 (Div. 2)','2000','Bitmask DP','','Misc 2000-2100','Phase C'],
    ['CF','1783D','Different Arrays','Codeforces Round 846 (Div. 2)','2100','DP + distinct values','','Misc 2000-2100','Phase C'],
    ['CF','1787D','The Awakening','Codeforces Round 848 (Div. 2)','2000','Graph + greedy','','Misc 2000-2100','Phase C'],
    ['CF','1793C','Removal of Unattractive Pairs','Codeforces Round 851 (Div. 2)','2000','Greedy + math','','Misc 2000-2100','Phase C'],
    ['CF','1798D','Shocking Arrangement','Codeforces Round 853 (Div. 2)','2100','Construction','','Misc 2000-2100','Phase C'],
    ['CF','1801D','Non-Decreasing Dilemma','Codeforces Round 854 (Div. 2)','2000','Binary search','','Misc 2000-2100','Phase C'],
    ['CF','1805D','A Wide Wide Graph','Codeforces Round 857 (Div. 2)','2000','Tree diameter','','Misc 2000-2100','Phase C'],
    ['CF','1806D','XOR-ranges','Codeforces Round 858 (Div. 2)','2100','Greedy on bits','','Misc 2000-2100','Phase C'],
    ['CF','1808D','Petya Petya and Petya','Codeforces Round 860 (Div. 2)','2100','Convex hull trick DP','','Misc 2000-2100','Phase C'],
    ['CF','1810D','Fake BST','Codeforces Round 861 (Div. 2)','2100','Recursion + combinatorics','','Misc 2000-2100','Phase C'],
    ['CF','1814D','Balancing Balls','Codeforces Round 864 (Div. 2)','2000','Greedy simulation','','Misc 2000-2100','Phase C'],
    ['CF','1819D','Misha and Apples','Codeforces Round 867 (Div. 2)','2000','DP on tree','','Misc 2000-2100','Phase C'],
    ['CF','1822D','Super Alien','Codeforces Round 869 (Div. 1)','2200','Bitset DP','','Misc 2000-2100','Phase C'],
    ['CF','1825D','Experience Acquisition','Codeforces Round 872 (Div. 2)','2100','Greedy + binary lifting','','Misc 2000-2100','Phase C'],
    ['CF','1830D','Flipping Range','Codeforces Round 876 (Div. 2)','2100','XOR + math','','Misc 2000-2100','Phase C'],
    // Phase D
    ['CF','1788D','Moving Dots','Codeforces Round 847 (Div. 2)','2200','Counting + product','','Elite 2200+','Phase D'],
    ['CF','1793D','Moscow is Melting','Codeforces Round 851 (Div. 1)','2200','Segment tree beats','','Elite 2200+','Phase D'],
    ['CF','1800D','Friendly Spiders','Codeforces Round 854 (Div. 1)','2200','Sieve + BFS','','Elite 2200+','Phase D'],
    ['CF','1815D','XOR-Query','Codeforces Round 866 (Div. 2)','2200','Offline + BIT','','Elite 2200+','Phase D'],
    ['CF','1835D','Reconstruct String','Codeforces Round 876 (Div. 1)','2200','Suffix array','','Elite 2200+','Phase D'],
    ['CF','1842D','Tenzing and Coins','Codeforces Round 878 (Div. 2)','2200','Inclusion-exclusion','','Elite 2200+','Phase D'],
    ['CF','1854D','Michael and Hotel','Codeforces Round 884 (Div. 2)','2200','LCT / offline','','Elite 2200+','Phase D'],
    ['CF','1863D','Divide-and-Conquer DP','Codeforces Round 892 (Div. 1)','2200','D&C DP optimization','','Elite 2200+','Phase D'],
    ['CF','1873D','Gossiping','Codeforces Round 896 (Div. 2)','2200','Math + modular','','Elite 2200+','Phase D'],
    ['CF','1879D','Sum of XOR Functions','Codeforces Round 899 (Div. 2)','2200','XOR + prefix sum','','Elite 2200+','Phase D'],
    ['CF','1891D','Progressions Covering','Codeforces Round 906 (Div. 2)','2200','Segment tree','','Elite 2200+','Phase D'],
    ['CF','1899D','Counting Binary Strings','Codeforces Round 910 (Div. 2)','2200','Digit DP','','Elite 2200+','Phase D'],
    ['CF','1904D','Professor Mad','Codeforces Round 914 (Div. 2)','2200','Sieve + greedy','','Elite 2200+','Phase D'],
    ['CF','1912D','Even Permutation','Codeforces Round 917 (Div. 2)','2200','Combinatorics','','Elite 2200+','Phase D'],
    ['CF','1921D','Maximum Distance','Codeforces Round 921 (Div. 2)','2300','Greedy + structures','','Elite 2200+','Phase D'],
    ['CF','1937D','Funny Game','Codeforces Round 929 (Div. 2)','2300','DP + complex transition','','Elite 2200+','Phase D'],
    ['CF','1942D','Road to Berland','Codeforces Round 933 (Div. 2)','2400','Flow / matching','','Elite 2200+','Phase D'],
    ['CF','1956D','Nene and Bit Operations','Codeforces Round 938 (Div. 2)','2400','Bitmask + game theory','','Elite 2200+','Phase D'],
    ['CF','1971D','Binary Alchemy','Codeforces Round 945 (Div. 2)','2200','Greedy + BFS','','Elite 2200+','Phase D'],
    ['CF','1977D','Colorful Stamp','Codeforces Round 950 (Div. 2)','2100','DSU','','Elite 2200+','Phase D'],
    ['CF','1982D','Niyaz and Chocolates','Codeforces Round 952 (Div. 2)','2200','DP + range trees','','Elite 2200+','Phase D'],
    ['CF','1989D','Masha and Flipping','Codeforces Round 956 (Div. 2)','2200','Math + greedy','','Elite 2200+','Phase D'],
    ['CF','1996E','Anyas Balloon','Codeforces Round 963 (Div. 2)','2200','Offline + segment tree','','Elite 2200+','Phase D'],
    ['CF','2000E','Subtree XOR','Codeforces Round 966 (Div. 2)','2200','Tree + XOR DP','','Elite 2200+','Phase D'],
    ['CF','2009D','Satyam and Counting','Codeforces Round 975 (Div. 2)','2100','Counting + greedy','','Elite 2200+','Phase D'],
    ['CF','2019D','Alternating Game','Codeforces Round 980 (Div. 2)','2200','Game theory','','Elite 2200+','Phase D'],
    ['CF','2030D','Min Cost Array','Codeforces Round 988 (Div. 2)','2200','Construction + math','','Elite 2200+','Phase D'],
    ['CF','2041D','Chain Swaps','Codeforces Round 992 (Div. 2)','2200','Greedy + Fenwick','','Elite 2200+','Phase D'],
    ['CF','2047D','Broken Clock','Codeforces Round 994 (Div. 2)','2200','Math + modular','','Elite 2200+','Phase D'],
    ['CF','2050D','Grid Coloring','Codeforces Round 996 (Div. 2)','2200','Construction','','Elite 2200+','Phase D'],
    ['CF','2058D','Tree Destruction','Codeforces Round 1000 (Div. 2)','2300','Tree DP','','Elite 2200+','Phase D'],
    ['CF','2066D','Sequence Counting','Codeforces Round 1003 (Div. 2)','2200','Digit DP','','Elite 2200+','Phase D'],
    ['CF','2073D','Array Inversion','Codeforces Round 1006 (Div. 2)','2200','Segment tree beats','','Elite 2200+','Phase D'],
    ['CF','2080D','K-Good Array','Codeforces Round 1009 (Div. 2)','2200','Number theory','','Elite 2200+','Phase D'],
    ['CF','2085D','Grid Partitioning','Codeforces Round 1012 (Div. 2)','2200','2D data structure','','Elite 2200+','Phase D'],
    ['CF','2091D','Palindrome Counting','Codeforces Round 1016 (Div. 2)','2300','Suffix array + hashing','','Elite 2200+','Phase D'],
    ['CF','2097D','Flow Balance','Codeforces Round 1019 (Div. 2)','2300','Min-cost flow','','Elite 2200+','Phase D'],
    ['CF','2103D','Subgraph Sum','Codeforces Round 1022 (Div. 2)','2400','Advanced graph DP','','Elite 2200+','Phase D'],
    ['CF','2110D','Merge Trees','Codeforces Round 1025 (Div. 2)','2400','Divide & conquer + LCT','','Elite 2200+','Phase D'],
    ['CF','2118D','Matrix Arrangement','Codeforces Round 1028 (Div. 2)','2400','Matching + flows','','Elite 2200+','Phase D'],
  ];

  const allProblems = [...lcProblems, ...cfProblems];
  for (const p of allProblems) {
    await pool.query(
      `INSERT INTO problems (type,number,name,contest,rating,topic,hft_relevance,category,phase) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
      p
    );
  }
  console.log(`Seeded ${allProblems.length} problems`);
}

// Routes
app.get('/api/problems', async (req, res) => {
  try {
    const { rows } = await pool.query('SELECT * FROM problems ORDER BY type, phase, id');
    res.json(rows);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.patch('/api/problems/:id', async (req, res) => {
  const { id } = req.params;
  const { solved, important, note } = req.body;
  try {
    const { rows } = await pool.query(
      `UPDATE problems SET solved=COALESCE($1,solved), important=COALESCE($2,important), note=COALESCE($3,note), updated_at=NOW() WHERE id=$4 RETURNING *`,
      [solved, important, note, id]
    );
    res.json(rows[0]);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.post('/api/problems', async (req, res) => {
  const { type, number, name, contest, rating, topic, hft_relevance, category, phase } = req.body;
  try {
    const { rows } = await pool.query(
      `INSERT INTO problems (type,number,name,contest,rating,topic,hft_relevance,category,phase) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,
      [type||'CF', number||'', name, contest||'', rating||'', topic||'', hft_relevance||'', category||'Custom', phase||'Custom']
    );
    res.json(rows[0]);
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.delete('/api/problems/:id', async (req, res) => {
  try {
    await pool.query('DELETE FROM problems WHERE id=$1', [req.params.id]);
    res.json({ ok: true });
  } catch (e) { res.status(500).json({ error: e.message }); }
});

app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));

initDB().then(seedProblems).then(() => {
  app.listen(3000, () => console.log('HFT Tracker running on http://localhost:3000'));
});
